# ---------------------------------------------------------------------------- #
#                                Navigation Bar                                #
# ---------------------------------------------------------------------------- #

navbar:
  # [always, auto]
  visiable: auto
  # [img] or [icon + title]
  logo:
    # img:
  menu:
    - name: 首页
      icon: fa-solid fa-house
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 关于
      icon: fa-solid fa-address-card
      url: about/
    - name: 暗黑模式
      icon: fas fa-moon
      toggle: darkmode
  search: 搜索...

# ---------------------------------------------------------------------------- #
#                                  Site Footer                                 #
# ---------------------------------------------------------------------------- #

site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [license, analytics, info, copyright]
  source: https://github.com/xueelf/xueelf.github.io
  analytics: >
    <span id="lc-sv">本站总访问量为 <span id='number'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span id="lc-uv">访客数为 <span id='number'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  copyright: "[Copyright © since 2022 Yuki](/)"
  br: "<br>"

# ---------------------------------------------------------------------------- #
#                                     Cover                                    #
# ---------------------------------------------------------------------------- #

cover:
  # full, half
  height_scheme: full
  # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  layout_scheme: search
  display:
    home: true
    archive: true
    others: true
  background: /images/pixiv/69707542.jpg
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: "Yuki 妙妙屋"
  subtitle: 不要因为走得太远，就忘了当初为什么出发。
  search: 搜索...
  features:
    - name: 首页
      icon: fa-solid fa-house
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 源码
      icon: fa-solid fa-code
      url: https://github.com/xueelf/xueelf.github.io

# ---------------------------------------------------------------------------- #
#                                    Sidebar                                   #
# ---------------------------------------------------------------------------- #

sidebar:
  # left right
  position: left
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud, donate]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://q1.qlogo.cn/g?b=qq&nk=2225151531&s=5
      shape: rectangle # circle, rectangle
      url: /about/
      title: Yuki
      subtitle: 大切な人と、いつかまた巡り会えますように。
      jinrishici: false
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fa-solid fa-envelope
          url: mailto:admin@yuki.sh
        - icon: fa-brands fa-github
          url: https://github.com/xueelf
        - icon: fa-brands fa-twitter
          url: https://twitter.com/xueelf
        - icon: fa-brands fa-weibo
          url: https://weibo.com/xueelf
        - icon: fa-brands fa-qq
          url: https://qm.qq.com/cgi-bin/qm/qr?k=bnBKJ_zXPQRhcKeT0GY_XoAUNmstlQ18&jump_from=webapi&authKey=3WebvjCThDFgvUFy1A0vtEh6t705eujE73jwMTAvQUbzQ9TVD5lzpgOq2vbas3cp
        - icon: fa-brands fa-bilibili
          url: https://space.bilibili.com/1414464
        - icon: fa-brands fa-steam
          url: https://steamcommunity.com/id/xueelf
        - icon: fa-solid fa-headphones-alt
          url: https://music.163.com/#/user/home?id=84724568
        - icon: fa-brands fa-telegram
          url: https://t.me/xueelf

# ---------------------------------------------------------------------------- #
#                                    Search                                    #
# ---------------------------------------------------------------------------- #

search:
  enable: true
  service: hexo

# ---------------------------------------------------------------------------- #
#                                Article Layout                                #
# ---------------------------------------------------------------------------- #

article:
  body:
    footer_widget:
      copyright:
        enable: true

# ---------------------------------------------------------------------------- #
#                                   Comments                                   #
# ---------------------------------------------------------------------------- #

comments:
  service: giscus
  giscus:
    repo: xueelf/xueelf.github.io
    repo-id: R_kgDOHPJkyA
    category: Announcements
    category-id: DIC_kwDOHPJkyM4Ca4sK
    mapping: "title"
    reactions-enabled: "1"
    emit-metadata: "0"
    lang: "zh-CN"

plugins:
  #   parallax:
  #     enable: true
  #     images:
  #       - /images/pixiv/62824816.jpg
  #       - /images/pixiv/69707542.jpg
  darkmode:
    enable: true

analytics:
  leancloud:
    app_id: 0dfitqFVnwsTtHuFIRbArRGg-MdYXbMMI
    app_key: V0hLKelWjzNhS68H8SmCVi4q
    custom_api_server:
